version: '3.4'

services:
    db:
        image: mysql:8.0.12
        ports:
            - '3306:3306'
        volumes:
            - './data:/var/lib/mysql:rw'
            - './my.cnf:/etc/mysql/conf.d/config-file.cnf'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: usf

    class-registry:
        build: .
        depends_on:
            - db
        volumes:
            - .:/usr/src/app
        ports:
            - 5000:80
        environment:
            WHAT_HOSTS: db:3306
